/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zhouzhe_testjni_CppNative */

#ifndef _Included_com_example_zhouzhe_testjni_CppNative
#define _Included_com_example_zhouzhe_testjni_CppNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zhouzhe_testjni_CppNative
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_zhouzhe_testjni_CppNative_getInt
  (JNIEnv *, jclass, jbyteArray, jstring, jclass);

#ifdef __cplusplus
}
#endif
#endif
